# Generated by Django 5.0.2 on 2024-02-19 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_record_remark_record_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='remark',
            field=models.TextField(blank=True, default=''),
        ),
    ]
