# Generated by Django 5.0.2 on 2024-02-24 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_alter_record_remark'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='file_upload',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='record',
            name='score',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=5),
        ),
    ]
