# Generated by Django 5.0.2 on 2024-03-25 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_alter_notification_options_alter_record_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='record',
            options={'ordering': ['created_at']},
        ),
    ]
