# Generated by Django 5.0.2 on 2024-05-08 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0007_alter_record_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="record",
            options={"ordering": ["-created_at"]},
        ),
    ]
